apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    run: elasticsearch
spec:
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
  selector:
    run: elasticsearch
  type: ClusterIP

